#![cfg_attr(not(feature = "std"), no_std)]
#![deny(
    warnings,
    unused,
    future_incompatible,
    nonstandard_style,
    rust_2018_idioms
)]
#![forbid(unsafe_code)]

//! This library implements an amicable pair of prime-order curves. This curve
//! cycle was generated by Daira Hopwood, and is also known as
//! [Tweedledum and Tweedledee](https://github.com/daira/tweedle).
//! The scalar field and base field of Tweedledum respectively equal the
//! base field and scalar field of Tweedledee.
//!
//! Curve information:
//! Tweedledum:
//! * Base field: p = 2^254 + 4707489545178046908921067385359695873
//! * Scalar field: q = 2^254 + 4707489544292117082687961190295928833
//! * Curve equation: y^2 = x^3 + 5
//! * Valuation(p - 1, 2) = 33
//! * Valuation(q - 1, 2) = 34
//!
//! Tweedledee:
//! * Base field: q = 2^254 + 4707489544292117082687961190295928833
//! * Scalar field: p = 2^254 + 4707489545178046908921067385359695873
//! * Curve equation: y^2 = x^3 + 5
//! * Valuation(p - 1, 2) = 33
//! * Valuation(q - 1, 2) = 34

#[cfg(feature = "curve")]
mod curves;
mod fields;

#[cfg(feature = "curve")]
pub use curves::*;
pub use fields::*;
